version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
      - ./php-ini/:/usr/local/etc/php/
      - ./logs/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysqldb
    networks:
      - frontend
      - backend
    ports:
      - "8077:80"
    volumes:
      - ./public_html/:/var/www/html/

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
            - ".env"
    environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
            - "./data/db/mysql:/var/lib/mysql"
    
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8011:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
        - mysqldb

networks:
  frontend:
  backend: